name: Build and Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Save the sercret file
        run: echo ${{ secrets.SECRET_FILE }} > ./functions/secret/test-secret2.json
      - name: Install Dependencies
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions:helloWorld,functions:helloWorld2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: githubactiontest-1c3bf
